pom.xml, server/pom.xml, server/src/main/java/org/bonitasoft/console/common/server/utils/ContractTypeConverter.java, server/src/main/java/org/bonitasoft/web/rest/server/api/bpm/flownode/UserTaskExecutionResource.java, server/src/main/java/org/bonitasoft/web/rest/server/api/bpm/process/ProcessInstantiationResource.java, server/src/test/java/org/bonitasoft/console/common/server/utils/ContractTypeConverterTest.java, server/src/test/java/org/bonitasoft/web/rest/server/api/bpm/flownode/UserTaskExecutionResourceTest.java, server/src/test/java/org/bonitasoft/web/rest/server/api/bpm/process/ProcessInstantiationResourceTest.java
Fixing support for numeric, dates, boolean and multiples when instantiating a contract of executing a task
=> Feat/bs 13018/support numeric in contract

forms/forms-view/src/main/java/org/bonitasoft/forms/client/view/common/DOMUtils.java
IE loses the focus of the input fields when a click is done on the load image on the screen during loading a Task.
=> BS-13249 IE loses the focus of the input fields

server/src/main/java/org/bonitasoft/console/common/server/page/CustomPageService.java, server/src/test/java/org/bonitasoft/console/common/server/page/CustomPageServiceTest.java, server/src/test/resources/ARootPageFolder/AbstractIndex.groovy, server/src/test/resources/ARootPageFolder/Index.groovy, server/src/test/resources/ARootPageFolder/org/company/test/Util.groovy, server/src/test/resources/ARootPageFolder/org/company/test/config.properties
Enables the possibilty to use a standard project hierachy for Rest api extensions:
Many source files and resources in packages (not only default package).
It doesn't break the runtime mechanism (with the Index.groovy).
Some integration test should be performed to check behavior when having jar dependencies.
=> BS-14501 add all groovy files in classpath

portal/src/main/java/org/bonitasoft/web/toolkit/client/ClientApplicationURL.java
BS-14583 - decode History token twice for FF41 and later
due tu this change in FF's behavior (and also latest Safari versions apparently):
https://www.fxsitecompat.com/en-US/docs/2015/urlutils-hash-no-longer-decodes-fragment/
=> BS-14583 - decode History token twice for FF41 and later

pom.xml, security-scripts/pom.xml, server/pom.xml
currently the version is not the same as the version used by restlet,
put it to 2.4.4
in addition the engine use also the 2.4.4 and need version >= 2.4.1 to
use the clearCache on TypeFactory to fix classloader leak
depends on https://github.com/bonitasoft/bonita-engine/pull/223
=> update jackson version to 2.4.4

server/src/main/java/org/bonitasoft/web/rest/server/api/resource/CommonResource.java, server/src/test/java/org/bonitasoft/web/rest/server/api/resource/CommonResourceTest.java
Instead of using the method getValues that concatenates all values into a single String, use the method getValuesArray that returns an array of values
=> BS-14712, allow query parameters to contain values with comma character

server/src/main/webapp/WEB-INF/web.xml
Allow to access to this servlet via ../API/API/formsDocumentImage in custom pages
Needed by https://github.com/bonitasoft/bonita-widget-contrib/pull/10
=> Add /API/formsDocumentImage url-pattern for formsDocumentImage servlet

looknfeel/src/main/less/skin/bootstrap/portal/applications/import.less
Added font-size to .upload-field input for ie only
Fixes [BS-13689](https://bonitasoft.atlassian.net/browse/BS-13689)
=> fix(BS-13689) On IE, Simple click is not working to upload a file

looknfeel/src/main/less/skin/bootstrap/portal/tasks/task-list.less
BS-14796 - fix modal task form close button
The button cannot be clicked because it is unreachable due to its floating position.
This PR applies clear: both attribute to the modal content so that it get displayed below the button and not over it
=> BS-14796 - fix modal task form close button

portal/src/main/java/org/bonitasoft/console/client/user/task/view/TasksListingPage.java
Only display completed tasks in the user profile task list when the done task filter is selected (aborted tasks shouldn't be displayed)
Fixes [BS-14834](https://bonitasoft.atlassian.net/browse/BS-14834)
=> BS-14834 - only display completed tasks

looknfeel/src/main/resources/BonitaConsole.html, looknfeel/src/main/resources/bonita_ie.css
Add a specific css for ie lower than ie11
Override .form-view css attributes to have the wanted height in ie
Fixes [BS-14894](https://bonitasoft.atlassian.net/browse/BS-14894)
=> fix(BS-14894) Cannot view complete overiew page of case in IE

bonita-home/src/main/resources/client/platform/tenant-template/conf/custom-permissions-mapping.properties, bonita-home/src/main/resources/client/platform/tenant-template/conf/dynamic-permissions-checks.properties, common/src/test/java/org/bonitasoft/console/common/server/preferences/properties/SimplePropertiesTest.java, common/src/test/resources/custom-permissions-mapping.properties
Special characters like white space must be replaced with their unicode value (For example \u0020 for the white space)
Add unit test and guidance in the properties files
covers [BS-15117](https://bonitasoft.atlassian.net/browse/BS-15117)
=> fix(BS-15117) Custom permissions mapping and profiles with spaces

forms/forms-server/src/main/java/org/bonitasoft/forms/server/filter/BPMURLSupportFilter.java
In case of a login with CAS, the URL get unnecessarily rewritten because the ticket parameter is not part of the supported parameters in the query string
=> TR/avoid rewriting URL with sso

server/src/main/java/org/bonitasoft/web/rest/server/api/resource/CommonResource.java, server/src/test/java/org/bonitasoft/web/rest/server/api/resource/CommonResourceTest.java
Parameters were incorrectly parsed for filters
Sorry for the addition of the "final" that should have been made in a separate commit
covers [BS-15218](https://bonitasoft.atlassian.net/browse/BS-15218)
=> fix(BS-15218) support task name with equals symbol in REST API

looknfeel/assemblyLESS.xml
In contrary to bonita.css, bootstrap.min.css is not compiled by portal while getting looknfeel from database.
That is why compiled bootstrap.min.css needs to be enbed in less archive.
Please also note that this is the less archive that is been used as portal looknfeel instead of css archive.
=> fix(looknfeel): add compiled bootstrap.css to less archive

common/src/main/java/org/bonitasoft/console/common/server/auth/impl/standard/StandardAuthenticationManagerImpl.java, common/src/main/java/org/bonitasoft/console/common/server/utils/PermissionsBuilder.java, common/src/main/java/org/bonitasoft/console/common/server/utils/PermissionsBuilderAccessor.java, common/src/main/java/org/bonitasoft/console/common/server/utils/PlatformManagementUtils.java, common/src/test/java/org/bonitasoft/console/common/server/utils/PermissionsBuilderAccessorTest.java, server/src/main/java/org/bonitasoft/console/common/server/login/filter/RestAPIAuthorizationFilter.java
when the debug mode is activated we reload security properties from the
database at each user login (i.e. when user permissions are construct)
=> feat(paas_ready): reload security properties in debug

server/src/main/java/org/bonitasoft/console/common/server/auth/impl/standard/StandardAuthenticationManagerImpl.java, server/src/test/java/org/bonitasoft/console/common/server/auth/impl/standard/StandardAuthenticationManagerImplTest.java
When current tenant is the defualt one, do not add tenant parameter in login url
Relates to [BS-8234](https://bonitasoft.atlassian.net/browse/BS-8234)
=> fix(multitenancy): remove tenantid from url when default

portal/src/main/java/org/bonitasoft/console/client/user/process/view/StartProcessFormPage.java
- add the postMessage event listener for task forms to the process form
iframe as with 6.x forms, you might end up with a task form inside the
process form iframe (by following the confirmation message link)
Covers [BS-15410](https://bonitasoft.atlassian.net/browse/BS-15410)
=> fix(BS-15410) Double menu after a sequence Form V6 + Form UIDesigner

forms/forms-server/src/main/java/org/bonitasoft/forms/server/api/impl/FormWorkflowAPIImpl.java, forms/forms-server/src/test/java/org/bonitasoft/forms/server/api/impl/FormWorkflowAPIImplTest.java
- restore call to isInvolvedInProcessInstance engine method in 6.x forms
for process instance overview access control
Covers [BS-15125](https://bonitasoft.atlassian.net/browse/BS-15125)
=> fix(BS-15125) restore call to isInvolvedInProcessInstance Method

server/src/main/java/org/bonitasoft/web/rest/server/datastore/organization/UserDatastore.java, server/src/main/java/org/bonitasoft/web/rest/server/datastore/organization/UserUpdaterConverter.java, server/src/test/java/org/bonitasoft/web/rest/server/datastore/organization/UserDatastoreTest.java
it is the same issue that happened on roles
Closes [BS-15474](https://bonitasoft.atlassian.net/browse/BS-15474)
=> fix(avatar): ignore icon on update  if empty

server/src/main/java/org/bonitasoft/web/rest/server/datastore/profile/PageLister.java
Make sure the names and descriptions of the default pages are clear enough in the profile edition popup. Especially the distinction between admin PM and user pages
Linked to  [bonitasoft/bonita-qa-tools#17](https://github.com/bonitasoft/bonita-qa-tools/pull/17)
=> feat(task-pages) Update default pages description for custom profiles

server/src/main/java/org/bonitasoft/web/rest/server/api/organization/APIUser.java, server/src/test/java/org/bonitasoft/web/rest/server/api/organization/APIUserTest.java, server/src/test/java/org/bonitasoft/web/rest/server/api/organization/TestValidator.java
we did not checked the password on update. the result is that if it was
empty the password was updated to an empty value.
fixed it, readded the checks that were removed following the refactor on
udpate user done during user icon migration in database.
Closes [BS-15530](https://bonitasoft.atlassian.net/browse/BS-15530)
=> fix(api_user): check if user password valid on update

portal/src/main/java/org/bonitasoft/console/client/user/task/action/TaskExecutionCallbackBehavior.java
When starting a process with a 6.x form, if you click on the link to the
task in the confirmation message you end up with a task form displayed
in the process start page. So the redirection to the task list should
take the process start page token into account
Covers [BS-15533](https://bonitasoft.atlassian.net/browse/BS-15533)
=> fix (BS-15533) No redirection to tasklist after submit form in Portal with 6.x instantiation form
