bonitasoft/bonita-web

server/src/main/java/org/bonitasoft/console/common/server/utils/ContractTypeConverter.java, server/src/test/java/org/bonitasoft/console/common/server/utils/ContractTypeConverterTest.java
=> BS-13014, BS-13015 - support dates in contract

looknfeel/src/main/less/skin/bootstrap/portal/process-more-details.less
=> changed style to be more bootstrap compliant

server/src/main/java/org/bonitasoft/console/common/server/utils/ContractTypeConverter.java, server/src/test/java/org/bonitasoft/console/common/server/utils/ContractTypeConverterTest.java, server/src/test/java/org/bonitasoft/web/rest/server/api/bpm/flownode/UserTaskContractResourceTest.java, server/src/test/java/org/bonitasoft/web/rest/server/api/bpm/flownode/UserTaskExecutionResourceTest.java, server/src/test/java/org/bonitasoft/web/rest/server/api/bpm/process/ProcessContractResourceTest.java, server/src/test/java/org/bonitasoft/web/rest/server/api/bpm/process/ProcessInstantiationResourceTest.java, server/src/test/resources/org/bonitasoft/web/rest/server/api/bpm/flownode/contract.json, server/src/test/resources/org/bonitasoft/web/rest/server/api/bpm/process/contract.json
Merge of complex and simple input definition into a single InputDefinition that has a method hasChildren()
=> Bs 13174 merge contract inputs

server/src/main/java/org/bonitasoft/console/common/server/page/PageMappingService.java, server/src/main/java/org/bonitasoft/console/common/server/page/PageServlet.java, server/src/test/java/org/bonitasoft/console/common/server/page/PageMappingServiceTest.java, server/src/test/java/org/bonitasoft/console/common/server/page/PageServletTest.java
Authorization rules should not be checked when trying to display a page resource
=> BS-13238 - Authorization rules should not be checked when trying to

server/src/main/java/org/bonitasoft/console/common/server/servlet/FileUploadServlet.java, server/src/main/webapp/WEB-INF/web.xml, server/src/test/java/org/bonitasoft/console/common/server/servlet/FileUploadServletTest.java
BS-13250 - Update TenantFileUploadServlet to support json as response content type
=> BS-13250 - Update TenantFileUploadServlet to support json as response

pom.xml
the time to build custom pages is now quite long and saving this time on dev time build may be smart
=> use appropriate modules on dev profile

server/src/main/java/org/bonitasoft/console/common/server/utils/ContractTypeConverter.java, server/src/test/java/org/bonitasoft/console/common/server/utils/ContractTypeConverterTest.java
TO DO: fix the test getProcessedInputs_with_multiple_complex_input_should_return_processed_input
=> Delete file after reading

server/src/main/java/org/bonitasoft/console/common/server/utils/ContractTypeConverter.java, server/src/test/java/org/bonitasoft/console/common/server/utils/ContractTypeConverterTest.java
use Integer type instead of Long for integer contract inputs
=> BS-13367 - Contract "integer" cannot be mapped to BDM "integer"

server/src/main/java/org/bonitasoft/console/common/server/utils/ContractTypeConverter.java, server/src/test/java/org/bonitasoft/console/common/server/utils/ContractTypeConverterTest.java
Remove constraint on NotNullable contract inputs
=> BS-13464 - Remove constraint on NotNullable contract inputs

server/src/main/java/org/bonitasoft/console/common/server/registration/BonitaRegistration.java, server/src/main/java/org/bonitasoft/web/rest/server/datastore/applicationmenu/ApplicationMenuDataStore.java, server/src/main/java/org/bonitasoft/web/rest/server/datastore/applicationpage/ApplicationPageDataStore.java, server/src/main/java/org/bonitasoft/web/rest/server/datastore/applicationpage/ApplicationPageDataStoreCreator.java, server/src/test/java/org/bonitasoft/console/common/server/registration/BonitaRegistrationTest.java, server/src/test/java/org/bonitasoft/web/rest/server/datastore/applicationpage/ApplicationPageDataStoreTest.java
Call the service when adding a custom page (not provided) to a living app
=> BS-13534 - Call the service when adding a custom page that is not

custom-pages/layout-page/src/main/resources/page.properties, custom-pages/theme-page/src/main/resources/page.properties
To be merged at same time as https://github.com/bonitasoft/bonita-web-sp/pull/17
=> BS-13697, rename default theme and layout

looknfeel/src/main/less/bootstrap/glyphicons.less, looknfeel/src/main/less/skin/skin.reset.less, looknfeel/src/main/resources/css/bootstrap.min.css
BS-13746 With IE Stacktrace in log about java.io.IOException: Invalid argument in BonitaHomeFolderAccessor.verifyFolderAuthorization
=> BS-13746 With IE Stacktrace in log about java.io.IOException: Invalid argument

server/src/main/java/org/bonitasoft/web/rest/server/api/bdm/MultipleBusinessDataReferenceClient.java, server/src/main/java/org/bonitasoft/web/rest/server/api/bdm/SimpleBusinessDataReferenceClient.java, server/src/test/java/org/bonitasoft/web/rest/server/api/bdm/BusinessDataReferenceResourceFinderTest.java, server/src/test/resources/org/bonitasoft/web/rest/server/api/bdm/multiRef.json, server/src/test/resources/org/bonitasoft/web/rest/server/api/bdm/refs.json, server/src/test/resources/org/bonitasoft/web/rest/server/api/bdm/simpleRef.json
needs to merge engine PR before:
https://github.com/bonitasoft/bonita-engine/pull/122
=> BS-13648, add string representation to business data references

server/src/main/webapp/WEB-INF/web.xml
in case token is requested from a Living application that forwards the request to the original API servlet
=> add forward dispatcher for TokenGeneratorFilter

portal/src/main/java/org/bonitasoft/console/client/ConsoleFactoryClient.java, portal/src/main/java/org/bonitasoft/console/client/angular/AngularIFrameView.java
=> BS-13890 Changed mapping for new case list

server/src/main/java/org/bonitasoft/console/common/server/login/servlet/PlatformLoginServlet.java, server/src/test/java/org/bonitasoft/console/common/server/login/servlet/PlatformLoginServletTest.java
on login on platform the servlet throw 403 instead of 500
not shure if it's the right way to throw error code from servlets..
depends on https://github.com/bonitasoft/bonita-engine/pull/149
=> BS-13435, throw 403 on wrong credentials

server/src/main/java/org/bonitasoft/console/common/server/utils/ContractTypeConverter.java, server/src/test/java/org/bonitasoft/console/common/server/utils/ContractTypeConverterTest.java
see also https://github.com/bonitasoft/bonita-engine/pull/155
=> BS-14119, set timezone to GMT for date converter instead of using server's locale

server/pom.xml, server/src/main/java/org/bonitasoft/console/common/server/servlet/FileUploadServlet.java, server/src/main/java/org/bonitasoft/console/common/server/servlet/PlatformFileUploadServlet.java, server/src/main/java/org/bonitasoft/console/common/server/servlet/TenantFileUploadServlet.java, server/src/test/java/org/bonitasoft/console/common/server/servlet/FileUploadServletTest.java, server/src/test/java/org/bonitasoft/console/common/server/servlet/TenantFileUploadServletTest.java
done the same way it was in legacy forms
=> control uploaded attachment file size

server/src/main/java/org/bonitasoft/web/rest/server/api/bdm/SimpleBusinessDataReferenceClient.java
No access to context object even if a single BDM object is not instantiated
=> BS-14000 - NPE on context retrieval

server/src/main/java/org/bonitasoft/console/common/server/servlet/FileUploadServlet.java, server/src/main/webapp/WEB-INF/web.xml, server/src/test/java/org/bonitasoft/console/common/server/servlet/TenantFileUploadServletTest.java
and fill response payload when type is json
=> throw a 413 error when uploaded file is too big

server/src/test/java/org/bonitasoft/console/common/server/servlet/TenantFileUploadServletTest.java
order to have test working with Java 8
=> BS-12336: the order of elements are not important, don'ty fix it in

server/src/main/java/org/bonitasoft/console/common/server/page/ChildFirstClassLoader.java, server/src/main/java/org/bonitasoft/console/common/server/page/CustomPageDependenciesResolver.java, server/src/main/java/org/bonitasoft/console/common/server/page/CustomPageService.java, server/src/test/java/org/bonitasoft/console/common/server/page/ChildFirstClassLoaderTest.java, server/src/test/java/org/bonitasoft/console/common/server/page/CustomPageDependenciesResolverTest.java, server/src/test/java/org/bonitasoft/console/common/server/page/CustomPageServiceTest.java, server/src/test/resources/ARootPageFolder/lib/subdir/resource.properties
Extract custom lib management.
Add unit tests
=> BS-14508 Refactor dependencies management for custom pages 

server/src/main/java/org/bonitasoft/console/common/server/login/filter/TokenGeneratorFilter.java, server/src/test/java/org/bonitasoft/console/common/server/login/filter/TokenGeneratorFilterTest.java
for angular to managing natively
=> add a cookie holding the bonita token CSRF token 

server/src/main/java/org/bonitasoft/console/common/server/page/CustomPageService.java, server/src/main/java/org/bonitasoft/console/common/server/page/RestApiRenderer.java, server/src/main/java/org/bonitasoft/web/rest/server/api/extension/ResourceExtensionResolver.java, server/src/main/java/org/bonitasoft/web/rest/server/datastore/page/PageDatastore.java, server/src/test/java/org/bonitasoft/console/common/server/page/CustomPageServiceTest.java, server/src/test/java/org/bonitasoft/web/rest/server/api/extension/ResourceExtensionResolverTest.java
* Allow filename with path (eg : org/company/rest/MyIndex.groovy)
=> BS-14620 Remove Index.groovy filename constraint for Rest API Extension

bonita-home/src/main/resources/client/platform/tenant-template/conf/console-config.properties, server/src/main/java/org/bonitasoft/console/common/server/servlet/TenantFileUploadServlet.java
Change also what tenant file upload servlet is using, was using the form
properties
=> Update the limite on file upload to 25MB

server/src/main/java/org/bonitasoft/console/common/server/page/RestApiRenderer.java, server/src/main/java/org/bonitasoft/console/common/server/page/extension/RestAPIContextImpl.java
https://github.com/bonitasoft/bonita-web-extensions/pull/4
=> BS-14742 Integrate new APIClient

portal/pom.xml
side effect of https://github.com/bonitasoft/bonita-web/pull/205 that introduce java 7 specific
=> set java version to 1.7 in portal

pom.xml, server/src/main/java/org/bonitasoft/console/common/server/servlet/FileUploadServlet.java, server/src/main/java/org/bonitasoft/console/common/server/servlet/PlatformFileUploadServlet.java, server/src/main/java/org/bonitasoft/console/common/server/servlet/TenantFileUploadServlet.java, server/src/test/java/org/bonitasoft/console/common/server/servlet/FileUploadServletTest.java, server/src/test/java/org/bonitasoft/console/common/server/servlet/TenantFileUploadServletTest.java
to response appropriate message
=> [BS-14134] catch OutOfMemoryError on big file upload

forms/forms-server/src/main/java/org/bonitasoft/forms/server/accessor/DefaultValidatorsProperties.java, forms/forms-server/src/main/java/org/bonitasoft/forms/server/api/impl/FormDefinitionAPIImpl.java, server/src/main/java/org/bonitasoft/console/server/service/ProcessActorImportService.java, server/src/main/java/org/bonitasoft/web/toolkit/server/ServletCall.java
DefaultValidatorsProperties.java, line 75
ProcessActorImportService.java, line 53
FormDefinitionAPIImpl.java, line 648
ServletCall.java, line 272
Fixes  [BS-14629](https://bonitasoft.atlassian.net/browse/BS-14629)
=> fix(BS-14629) Unreleased Resource: Streams

pom.xml, server/pom.xml
see https://issues.apache.org/jira/browse/COLLECTIONS-580
=> BS-14904 - Upgrade commons-collections version to 3.2.2

portal/src/main/java/org/bonitasoft/console/client/admin/page/view/DeleteCustomPage.java, portal/src/main/java/org/bonitasoft/console/client/user/cases/view/AbstractOverviewFormMappingRequester.java, portal/src/main/java/org/bonitasoft/console/client/user/task/action/CheckFormMappingAndDisplayPerformTaskPageAction.java, portal/src/main/java/org/bonitasoft/console/client/user/task/action/CheckFormMappingAndDisplayProcessInstanciationFormAction.java, portal/src/main/java/org/bonitasoft/web/toolkit/client/RequestBuilder.java, portal/src/main/java/org/bonitasoft/web/toolkit/client/data/api/request/HttpRequest.java, portal/src/test/java/org/bonitasoft/web/toolkit/client/RequestBuilderTest.java
BS-14999 - add API token for all request made with RequestBuilder (not going through web toolkit)
=> BS-14999 - add API token for all request made with RequestBuilder

looknfeel/src/main/resources/BonitaConsole.html, looknfeel/src/main/resources/bonita_ie.css
Add a specific css for ie lower than ie11
Override .form-view css attributes to have the wanted height in ie
=> fix(BS-14894) Cannot view complete overiew page of case in IE

portal/src/main/java/org/bonitasoft/console/client/technicaluser/businessdata/BDMImportWarningPopUp.java, portal/src/main/java/org/bonitasoft/web/toolkit/client/data/api/callback/HttpCallback.java
Closes [BS-15160](https://bonitasoft.atlassian.net/browse/BS-15160)
=> fix(bdm): add loader while deploying bdm

common/src/main/java/org/bonitasoft/console/common/server/preferences/properties/ConfigurationFilesManager.java, common/src/main/java/org/bonitasoft/console/common/server/utils/PlatformManagementUtils.java, common/src/test/java/org/bonitasoft/console/common/server/preferences/properties/ConfigurationFilesManagerTest.java, common/src/test/java/org/bonitasoft/console/common/server/utils/PlatformManagementUtilsTest.java
when properties like security mapping are updated the engine is called
in order to update them in database
=> feat(paas_read): call engine to update the configuration files

server/src/test/java/org/bonitasoft/console/common/server/auth/impl/standard/StandardAuthenticationManagerImplTest.java, server/src/test/java/org/bonitasoft/console/common/server/login/filter/AuthenticationFilterTest.java
Fixes failing tests intreoduced by commit [de33a9fb22e187e703901bc7e4e963364ef37ada](https://github.com/bonitasoft/bonita-web/pull/256/commits/de33a9fb22e187e703901bc7e4e963364ef37ada)
=> test(multitenancy): fix failing tests

forms/forms-view/src/main/java/org/bonitasoft/forms/client/view/widget/RadioButtonGroupWidget.java
Stop updating the value and triggering events if the value of the
radio button group did not change
fixes [BS-15253](https://bonitasoft.atlassian.net/browse/BS-15253)
=> fix(BS-15253) Show when a trigger radio button group has changed generates a NPE

server/src/test/resources/theme/BonitaForm.html
=> fix: change forms v6 footer copyrights to 2016

server/src/test/resources/theme/BonitaForm.html
Reverts bonitasoft/bonita-web#264
=> Revert "fix: change forms v6 footer copyrights to 2016"

forms/forms-model/src/main/java/org/bonitasoft/forms/client/model/FormWidget.java, forms/forms-model/src/main/java/org/bonitasoft/forms/client/model/ReducedFormWidget.java
required for PR: bonitasoft/bonita-web-sp/pull/74
covers [BS-15253](https://bonitasoft.atlassian.net/browse/BS-15253)
=> fix(BS-15253) add accessor to know if a widget has a value after event expression

portal/src/main/java/org/bonitasoft/console/client/user/process/action/ProcessInstantiationCallbackBehavior.java
With UID process start forms designed before 7.3, if you don't re-import
them into the UID, the case Id is not necessarily set in the post
Message sent by the pbButton. As a result, the portal is unable to
redirect to the details view of the case.
This PR allows to redirect to the home page of the current profile
instead of doing nothing (and potentially having the portal displayed
inside the portal if the targetURL on success of the form was set to
/bonita)
Covers [BS-15313](https://bonitasoft.atlassian.net/browse/BS-15313)
=> fix(BS-15313) handle the case were the caseID is not sent in the postMessage

forms/forms-server/src/test/java/org/bonitasoft/forms/server/api/impl/FormWorkflowAPIImplIT.java, test-toolkit/src/main/java/org/bonitasoft/test/toolkit/bpm/TestHumanTask.java
task are executed asynchonously on api call, changed the tests that
expected the task to be finished after the call to execute
=> test(task_exec): update test after change on asynch task exec

common/src/main/java/org/bonitasoft/console/common/server/utils/PlatformManagementUtils.java
follow engine changes
Closes [BS-15212](https://bonitasoft.atlassian.net/browse/BS-15212)
=> feat(paas_read): refactor local login system

portal/src/main/java/org/bonitasoft/console/client/menu/view/navigation/MenuListCreator.java, portal/src/main/java/org/bonitasoft/web/toolkit/client/ClientApplicationURL.java
=> fix(portal-nav) Display first page without messing up history

portal/src/main/java/org/bonitasoft/console/client/menu/view/navigation/MenuListCreator.java, portal/src/main/java/org/bonitasoft/web/toolkit/client/ClientApplicationURL.java
Reverts bonitasoft/bonita-web#277
=> Revert "fix(portal-nav) Display first page without messing up history"

portal/src/main/java/org/bonitasoft/console/client/admin/profile/action/AddProfileMemberAction.java, server/src/main/java/org/bonitasoft/web/rest/server/engineclient/ProfileMemberEngineClient.java
Closes [BS-15452](https://bonitasoft.atlassian.net/browse/BS-15452)
=> fix(profile-member) Display message when profile member already exist

common/src/main/java/org/bonitasoft/console/common/server/servlet/ResourceServlet.java, server/src/main/java/org/bonitasoft/console/common/server/page/PageResourceServlet.java, server/src/main/webapp/error-pages/500.jsp
Closes [BS-15362](https://bonitasoft.atlassian.net/browse/BS-15362)
=> fix(error-page) XSS issue when displaying exception message

server/src/main/java/org/bonitasoft/web/rest/server/utils/DataInstanceSerializer.java, server/src/main/java/org/bonitasoft/web/rest/server/utils/JacksonSerializerHelper.java, server/src/main/java/org/bonitasoft/web/rest/server/utils/TimerEventTriggerInstanceSerializer.java, server/src/test/java/org/bonitasoft/web/rest/server/api/bpm/flownode/ActivityVariableResourceTest.java, server/src/test/resources/org/bonitasoft/web/rest/server/api/bpm/flownode/nullDataInstance.json, server/src/test/resources/org/bonitasoft/web/rest/server/api/bpm/flownode/stringDataInstance.json
- Handle the case where the variable value is null
- add unit test
Covers [BS-15447](https://bonitasoft.atlassian.net/browse/BS-15447)
=> fix(BS-15447) Invalid JSON produced by /API/bpm/activityVariable when process variable is null

common/src/main/java/org/bonitasoft/console/common/server/preferences/constants/WebBonitaConstants.java, common/src/main/java/org/bonitasoft/console/common/server/preferences/constants/WebBonitaConstantsImpl.java, common/src/main/java/org/bonitasoft/console/common/server/preferences/constants/WebBonitaConstantsTenancyImpl.java, common/src/main/java/org/bonitasoft/console/common/server/preferences/constants/WebBonitaConstantsUtils.java, server/src/main/java/org/bonitasoft/console/common/server/servlet/PlatformTenantListener.java
Is part of [BS-14903](https://bonitasoft.atlassian.net/browse/BS-14903)
also merge https://github.com/bonitasoft/bonita-engine-sp/pull/261
and https://github.com/bonitasoft/bonita-web-sp/pull/87
=> Clean portal temporary files at JVM shutdown

portal/src/main/java/org/bonitasoft/console/client/user/process/action/ProcessInstantiationCallbackBehavior.java
I need to stay on the process list
Covers [BS-15539](https://bonitasoft.atlassian.net/browse/BS-15539)
Should be merged with bonitasoft/bonita-web-sp/pull/93
=> feat(case start) As Andy, when I start a case from Portal process list,
